[package]
name = "ruget"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", features = ["blocking", "json"] }
clap = { version = "4.5", features = ["derive"] }
indicatif = "0.17"
tokio = { version = "1.45", features = ["full"] }